name: Build and deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: master
      - uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin/wasm-pack
            master/target
          key: ${{ runner.os }}-rust-${{ hashFiles('master/Cargo.lock') }}

      - name: Install deps and build
        working-directory: "${{ github.workspace }}/master"
        run: |
          test -f ~/.cargo/bin/wasm-pack || cargo install wasm-pack
          yarn
          yarn build

      - name: Commit and push to gh-pages
        working-directory: "${{ github.workspace }}/gh-pages"
        run: |
          git ls-files | xargs rm
          cp $GITHUB_WORKSPACE/master/dist/* .
          git config --global user.email "16608915+JonasBak@users.noreply.github.com"
          git config --global user.name "Actions"
          git add .
          git commit --allow-empty -m "Deploy ${GITHUB_SHA:0:7} to github pages"
          git push
